apiVersion: v1
kind: Secret
metadata:
  name: skyline-rush-secrets
  namespace: skyline-rush-prod
  labels:
    app.kubernetes.io/name: skyline-rush
type: Opaque
stringData:
  POSTGRES_USER: "${POSTGRES_USER}"
  POSTGRES_PASSWORD: "${POSTGRES_PASSWORD}"
  POSTGRES_DB: "${POSTGRES_DB}"
  POSTGRES_URL: "postgresql://${POSTGRES_USER}:${POSTGRES_PASSWORD}@postgres-service.skyline-rush-prod.svc.cluster.local:5432/${POSTGRES_DB}"
  REDIS_PASSWORD: "${REDIS_PASSWORD}"
  REDIS_URL: "redis://:${REDIS_PASSWORD}@redis-service.skyline-rush-prod.svc.cluster.local:6379"
  JWT_SECRET: "${JWT_SECRET}"
  REFRESH_SECRET: "${REFRESH_SECRET}"
  PARENTAL_GATE_SECRET: "${PARENTAL_GATE_SECRET}"
